USE CS1333612;
DROP TABLE IF EXISTS Email;
DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS EmailAddress;
DROP TABLE IF EXISTS Attachments;
DROP TABLE IF EXISTS EmbeddedAttachments;
DROP TABLE IF EXISTS Folder;

CREATE TABLE Email
(
	emailId int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    emailsubject VARCHAR(255),
	emailSentDate TIMESTAMP,
	emailRcvdDate TIMESTAMP
);

CREATE TABLE Messages
(
	messageId int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    emailId int,
    emailText TEXT
);

CREATE TABLE EmailAddress
(
	emailAddressId int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    address VARCHAR(255),
    emailType VARCHAR(255),
	emailId int,
	sentAddress VARCHAR(255)
);

CREATE TABLE Attachments
(
	attachmentId int PRIMARY KEY AUTO_INCREMENT,
    messageFile MEDIUMBLOB,
	messageId int
);

CREATE TABLE Folder
(
	folderId int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    folderName VARCHAR(255)
);

ALTER TABLE EMAILADDRESS
ADD CONSTRAINT fk_emailAddress_emailId
FOREIGN KEY (emailId)
REFERENCES EMAIL(emailId)
ON DELETE CASCADE;

ALTER TABLE MESSAGES
ADD CONSTRAINT fk_emailId
FOREIGN KEY (emailId)
REFERENCES EMAIL(emailId)
ON DELETE CASCADE;

ALTER TABLE FOLDER
ADD CONSTRAINT fk_folder_emailId
FOREIGN KEY (emailId)
REFERENCES EMAIL(emailId)
ON DELETE CASCADE;

ALTER TABLE ATTACHMENTS
ADD CONSTRAINT fk_messageId
FOREIGN KEY (messageId)
REFERENCES MESSAGES(emailId)
ON DELETE CASCADE;